
# 向量数据库的名称
collection_name: agent


#向量数据库的存储路径
#Chroma会把 embedding 存到这个文件夹
persist_directory: chroma_db
k: 3
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: ["txt", "pdf"]

chunk_size: 200
chunk_overlap: 20
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]
